server:
  port: 8081

spring:
  datasource:
    name: db
    url: jdbc:mysql://127.0.0.1:3306/managedatasource?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: wl2018!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
      prefix: "classpath:/templates/"
      suffix: ".html"
      mode: HTML
      encoding: UTF-8
      content-type: text/html
      cache: false

mybatis:
  mapperLocations: classpath:mapping/*.xml